version: '3'

services:
    symfony_bench_be_nginx:
        container_name: symfony_bench_be_nginx
        image: nginx:stable
        networks:
            - symfony_bench_be_network
            - symfony_bench
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker/nginx/certs/cert.pem:/etc/nginx/certs/cert.pem
            - ./docker/nginx/certs/key.pem:/etc/nginx/certs/key.pem
        working_dir: /etc/nginx/conf.d

    symfony_bench_be_phpfpm:
        container_name: symfony_bench_be_phpfpm
        build:
            context: ./docker/phpfpm
        expose:
            - 9000
        networks:
            - symfony_bench_be_network
            - symfony_bench
        volumes:
            - .:/var/www/html:cached
        working_dir: /var/www/html

networks:
    symfony_bench_be_network:
        driver: bridge
    symfony_bench:
        external: true
