helloworld:
    path: /benchmark/helloworld
    controller: App\Controller\HelloWorldController


symfony_bench_test:
    path: '/test'
    methods: GET
    controller: App\Controller\PhpInfoController
